DROP TABLE IF EXISTS specials;
CREATE TABLE specials (id integer PRIMARY KEY,make text,thumb text,headline text,description text,leorder integer);
INSERT INTO specials ( id,make,thumb,headline,description,leorder ) VALUES ( '1','audi','R8Coupe.jpg','Audi A3 - Special $349 Lease now available','$350 Security Deposit<br />$349 First Month Payment<br />$695 Acquisition Fee<br />$2.499 Down Payment<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />$695 Acquisition Fee<br />$2.499 Down Payment<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)','1' );
INSERT INTO specials ( id,make,thumb,headline,description,leorder ) VALUES ( '2','audi','A4Avant.jpg','Audi A3 - Special $349 Lease now available','$350 Security Deposit<br />$349 First Month Payment<br />$695 Acquisition Fee<br />$2.499 Down Payment<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />','2' );
INSERT INTO specials ( id,make,thumb,headline,description,leorder ) VALUES ( '3','audi','A3Sportback.jpg','Audi A3 - Special $349 Lease now available','$350 Security Deposit<br />$349 First Month Payment<br />$695 Acquisition Fee<br />$2.499 Down Payment<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />','3' );
INSERT INTO specials ( id,make,thumb,headline,description,leorder ) VALUES ( '4','vw','R8Coupe.jpg','VW - Special $349 Lease now available','$350 Security Deposit<br />$349 First Month Payment<br />$695 Acquisition Fee<br />$2.499 Down Payment<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />','1' );
INSERT INTO specials ( id,make,thumb,headline,description,leorder ) VALUES ( '5','audi','S4Sedan.jpg','Audi A3 - Special $349 Lease now available','$350 Security Deposit<br />$349 First Month Payment<br />$695 Acquisition Fee<br />$2.499 Down Payment<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />','4' );
INSERT INTO specials ( id,make,thumb,headline,description,leorder ) VALUES ( '6','audi','S5Coupe.jpg','Audi A3 - Special $349 Lease now available','$350 Security Deposit<br />$349 First Month Payment<br />$695 Acquisition Fee<br />$2.499 Down Payment<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />','5' );
INSERT INTO specials ( id,make,thumb,headline,description,leorder ) VALUES ( '7','audi','AV5Coupe.jpg','Audi A3 - Special $349 Lease now available','$350 Security Deposit<br />$349 First Month Payment<br />$695 Acquisition Fee<br />$2.499 Down Payment<br />$3,893 Due at Signing* (Excludes taxes, title, other options and dealer fees)<br />','6' );
